define('res/js/common/constants', [], function() {

    return {
        PC: ['6.3.0', '6.2.0', '6.1.0', '6.0.0', '5.1.0'],
        SERVER: ['5.0.1', '6.3.1', '5.2.1', '5.2.1', '6.1.1', '6.0.1', '6.2.1'],
        PROTECTION_IGNORE: ['homepage', 'defaultbrowser', 'defaultsearch', 'arp', 'camera'],
        FUNC_LIST: [{
            "action": "1",
            "name": "360USBRescue"
        }, {
            "action": "1",
            "name": "360ask"
        }, {
            "action": "1",
            "name": "360HealthElf"
        }, {
            "action": "1",
            "name": "360MobileAssistant"
        }, {
            "action": "1",
            "name": "360PrivacyGuard"
        }, {
            "action": "1",
            "name": "360Compress"
        }, {
            "action": "1",
            "name": "360WifiExamine"
        }, {
            "action": "1",
            "name": "360cloud"
        }, {
            "action": "1",
            "name": "SoftMove"
        }, {
            "action": "1",
            "name": "360UDiskCheck"
        }, {
            "action": "1",
            "name": "360Wipe"
        }, {
            "action": "1",
            "name": "WangSuCeShiQi"
        }, {
            "action": "1",
            "name": "360DnsOpt"
        }, {
            "action": "1",
            "name": "360LuDaShi"
        }, {
            "action": "1",
            "name": "DefaultSoftSetting"
        }, {
            "action": "1",
            "name": "360Drvmgr"
        }, {
            "action": "1",
            "name": "JingChengGuangLi"
        }, {
            "action": "1",
            "name": "360SysClean"
        }, {
            "action": "1",
            "name": "360SysReset"
        }, {
            "action": "1",
            "name": "360Recovery"
        }, {
            "action": "1",
            "name": "360Calendar"
        }, {
            "action": "1",
            "name": "InstallOneKey"
        }, {
            "action": "1",
            "name": "360RegClean"
        }, {
            "action": "1",
            "name": "360LWiFi"
        }, {
            "action": "1",
            "name": "softmgr"
        }, {
            "action": "1",
            "name": "360JiShi"
        }, {
            "action": "1",
            "name": "mobile"
        }, {
            "action": "1",
            "name": "PopWndTracker"
        }, {
            "action": "1",
            "name": "sandbox"
        }, {
            "action": "1",
            "name": "softlite"
        }, {
            "action": "1",
            "name": "360MainPageRepair"
        }, {
            "action": "1",
            "name": "RouterAssistant"
        }, {
            "action": "1",
            "name": "360NetRepair"
        }, {
            "action": "1",
            "name": "LiuLiangJianKong"
        }, {
            "action": "1",
            "name": "LSPXiuFu"
        }, {
            "action": "1",
            "name": "LargeFileMgr"
        }, {
            "action": "1",
            "name": "360XiTongJiJiuXiang"
        }, {
            "action": "1",
            "name": "360Root"
        }, {
            "action": "1",
            "name": "360searchdesktop"
        }, {
            "action": "1",
            "name": "WenJianFenSuiJi"
        }]
    };

});